version: '3.4'

services:
  
  micro:
    image: hbtlabs/micro
    build:
      context: .
    container_name: micro
    command: server
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
